apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/web-app-metrics-cicd-argocd
    targetRevision: HEAD
    path: k8s
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
